language: python
python:
  - '2.7'
  - '3.2'
  - '3.4'
services:
  - elasticsearch
install:
  - pip install 'coverage<4'
  - travis_retry pip install -e .
  - travis_retry pip install file://$(pwd)#egg=djesrf[dev]
script:
  - py.test tests/
sudo: false
